title: Packet Route
description: AP CSP student blog
baseurl: "/packet-route"
url: "https://[your-username].github.io"

theme: minima

plugins:
  - jekyll-feed

permalink: /posts/:title/

header_pages:
  - essentials.md
  - packet-feed.md
  - innovations.md

collections:
  innovations:
    output: true
    permalink: /innovations/:name/

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "AP CSP Class"
  - scope:
      path: ""
      type: "innovations"
    values:
      layout: "post"
